var mdlVersion = '1.0.6';
var revision = 3;
var assetRevision = 0;

var mdlDistPath = 'dist'; // This relies on the symlink.
var mdlSrcPath = 'src'; // This relies on the symlink.

var packageVersion = (revision > 0) ? mdlVersion + '_' + revision : mdlVersion,
    assetPackageVersion = (assetRevision > 0) ? mdlVersion + '_' + assetRevision : mdlVersion;

Package.describe({
  name: 'zodiase:mdl',
  version: packageVersion,
  summary: 'A wrapper package for Google\'s Material Design Lite.',
  git: 'https://github.com/Zodiase/meteor-mdl.git',
  documentation: 'README.md'
});

Package.onUse(function (api) {
  'use strict';
  api.versionsFrom('1.2.1');
  api.use('isobuild:compiler-plugin@1.0.0');
  api.use('zodiase:mdl-assets@' + assetPackageVersion);
  api.use('fourseven:scss@3.4.1');

  api.export(['MDl'], 'client');

  api.addFiles([
    'setup.js',
    'check.js'
  ], 'client');

  // Patchers.
  api.addFiles([
    'patchers/blaze.js'
  ], 'client');

  // Add fonts for material icons.
  api.addAssets(fontAssets, 'client');
  api.addFiles('material-icons.css', 'client');

  // Add files to be imported by others.
  api.addFiles(prepandPathToFiles(importFiles, mdlSrcPath), 'client', {isImport: true});

  // Add other mdl assets.
  api.addAssets(prepandPathToFiles(mdlAssets, mdlSrcPath), ['client', 'server']);
  // Add helper scss file for fixing asset loading path.
  api.addFiles('theme.scss', 'client', {isImport: true});
});

Package.onTest(function (api) {
  api.use('tinytest');
  api.use('jquery');
  api.use('zodiase:mdl');
  api.addFiles([
    'tests/export.js',
    'tests/patcher-blaze.js'
  ], 'client');
});

function getThemeFileName(primary, accent) {
  return 'material.' + primary + '-' + accent + '.min.css';
}
function prepandPathToFiles(files, path) {
  var npmPath = Npm.require('path');
  return files.map(function(file) {
    return npmPath.join(path, file);
  });
}

Npm.depends({
  'material-design-lite': '1.0.6'
});

Package.registerBuildPlugin({
  name: 'build',
  use: [
    'ecmascript',
    'ejson',
    'sha',
    'zodiase:check',
    'zodiase:mdl-assets@' + assetPackageVersion
  ],
  sources: [
    'plugin/build.js'
  ],
  npmDependencies: {
    'extend': '3.0.0',
    'clone': '1.0.2'
  }
});

// The following code are generated by scripts. Do not manually edit. Run the scripts instead.
var fontAssets = [];
///>>>>FONTASSETS
fontAssets = ["fonts/2fcrYFNaTjcS6g4U3t-Y5UEw0lE80llgEseQY3FEmqw.woff2","fonts/2fcrYFNaTjcS6g4U3t-Y5ewrjPiaoEww8AihgqWRJAo.woff","fonts/2fcrYFNaTjcS6g4U3t-Y5RV6cRhDpPC5P4GCEJpqGoc.woff"];
///<<<<FONTASSETS
var importFiles = [];
///>>>>IMPORTFILES
importFiles = ["_color-definitions.scss","_functions.scss","_mixins.scss","_variables.scss","material-design-lite-grid.scss","material-design-lite.scss","styleguide.scss","template.scss","animation/_animation.scss","badge/_badge.scss","button/_button.scss","card/_card.scss","checkbox/_checkbox.scss","data-table/_data-table.scss","footer/_mega_footer.scss","footer/_mini_footer.scss","grid/_grid.scss","icon-toggle/_icon-toggle.scss","layout/_layout.scss","menu/_menu.scss","palette/_palette.scss","progress/_progress.scss","radio/_radio.scss","resets/_h5bp.scss","resets/_mobile.scss","resets/_resets.scss","ripple/_ripple.scss","shadow/_shadow.scss","slider/_slider.scss","spinner/_spinner.scss","switch/_switch.scss","tabs/_tabs.scss","textfield/_textfield.scss","tooltip/_tooltip.scss","typography/_typography.scss"];
///<<<<IMPORTFILES
var mdlAssets = [];
///>>>>MDLASSETS
mdlAssets = ["images/buffer.svg","images/tick-mask.svg","images/tick.svg"];
///<<<<MDLASSETS